#!/usr/bin/env -S npx tsx
/**
 * nginx-setup.ts — generates per-app nginx site configs for every package.
 *
 *  It reads:
 *   - .env              for VA_DOMAIN (falls back to localhost)
 *   - package compose.yaml files      for service name + host port
 *
 * Output:  nginx/conf.d/<service>.conf   (http -> https redirect + ssl server block)
 * Usage:   npx tsx nginx-setup.ts
 */
import { readdirSync, readFileSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const env = parseEnv(join(root, ".env"));
const domain = env.VA_DOMAIN || "localhost";
const outDir = join(root, "nginx", "conf.d");

function parseEnv(file: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(file)) return out;
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

/** Extract first host port mapping "HOST:CONTAINER" from a compose file. */
function hostPort(composeFile: string): string | null {
  if (!existsSync(composeFile)) return null;
  const text = readFileSync(composeFile, "utf8");
  const m = /["']?(\d+):\d+["']?/.exec(text);
  return m ? m[1] : null;
}

/** First service name under `services:` in a compose file. */
function serviceName(composeFile: string): string | null {
  if (!existsSync(composeFile)) return null;
  const text = readFileSync(composeFile, "utf8");
  const m = /services:\s*\n\s*([\w.-]+):/.exec(text);
  return m ? m[1] : null;
}

function serverBlock(name: string, port: string): string {
  const sslCert = `/etc/letsencrypt/live/${name}.${domain}/fullchain.pem`;
  const sslKey = `/etc/letsencrypt/live/${name}.${domain}/privkey.pem`;
  return `# Generated by nginx-setup.ts — ${name}.${domain} -> :${port}
server {
    listen 80;
    server_name ${name}.${domain};
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${name}.${domain};

    ssl_certificate     ${sslCert};
    ssl_certificate_key ${sslKey};

    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    gzip on;
    gzip_types application/json application/javascript text/plain text/css text/html;
}
`;
}

function collect(globDir: string): Array<[string, string]> {
  const found: Array<[string, string]> = [];
  if (!existsSync(globDir)) return found;
  for (const entry of readdirSync(globDir)) {
    const dir = join(globDir, entry);
    const compose = join(dir, "compose.yaml");
    const name = serviceName(compose) ?? entry;
    const port = hostPort(compose);
    if (port) found.push([name, port]);
  }
  return found;
}

mkdirSync(outDir, { recursive: true });

const apps: Array<[string, string]> = [
  ...collect(join(root, "packages", "web")),
  ...collect(join(root, "packages", "backend")),
];

let written = 0;
for (const [name, port] of apps) {
  const file = join(outDir, `${name}.conf`);
  writeFileSync(file, serverBlock(name, port));
  console.log(`  nginx/conf.d/${name}.conf  (${name}.${domain} -> :${port})`);
  written++;
}

console.log(`\n[nginx-setup] wrote ${written} config(s) to ${outDir}`);
if (!domain || domain === "localhost") {
  console.log("  tip: set VA_DOMAIN in .env and re-run for real domains.");
}
if (written === 0) {
  console.log("  (no packages with a host port found yet — run setup-project first)");
}
